### ISSUE TITLE
Could you tell me what's wrong with it? Thanks for your attention!

### ISSUE THREAD

**Issue by xiaoqun-growing** [whyisyoung/CADE#2]
Traceback (most recent call last):
  File "/home/anaconda3/envs/cade-gpu/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/anaconda3/envs/cade-gpu/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/anaconda3/envs/cade-gpu/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/home/anaconda3/envs/cade-gpu/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/home/anaconda3/envs/cade-gpu/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: libcudnn.so.7: cannot open shared object file: No such file or directory

**Comment by whyisyoung** [comment]
Hi,

Thanks for your interest in our code.
Could you try some of the solutions here: https://github.com/tensorflow/tensorflow/issues/20271
You need to find out where is the `libcudnn.so.7` and add the path to `LD_LIBRARY_PATH`.

Hope it helps!

**Comment by xiaoqun-growing** [comment]
OK, it is my fault. I just download  [cuDNN v7.3.1 Library for Linux](https://developer.nvidia.com/compute/machine-learning/cudnn/secure/v7.3.1/prod/9.0_2018927/cudnn-9.0-linux-x64-v7.3.1.20) and add the file to LD_LIBRARY_PATH. Everything is ok! Thank you !
